spring.application.name=sgp-api

spring.datasource.url=jdbc:mysql://localhost:3306/sgp_db

spring.datasource.username=root
spring.datasource.password=Abacaxi1603!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080